on: [push]

jobs:
  build_job:
    runs-on: ubuntu-latest
    name:  Build with Jenny
    steps:
    - uses: actions/checkout@v4
    - uses: hmngwy/jenny@master
    - uses: JamesIves/github-pages-deploy-action@master
      with:
        branch: main
        folder: .dist # The folder the action should deploy.

